# Generated by Django 6.0.3 on 2026-04-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('ai_decision', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('EXCHANGE', 'Exchange'), ('ESCALATE', 'Escalate'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('ai_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
